- name: Create /chatapp directory
  file:
    path: /chatapp
    state: directory
    owner: harman
    group: harman

- name: Clone React app repository from GitHub
  git:
    repo: https://github.com/WebDevSimplified/Whatsapp-Clone.git
    dest: /chatapp  # The destinationere you want to clone the repository
    version: main  # The branch or tag you want to clone (e.g., master, main)
  become: yes  # To run the task with elevated privileges
  become_user: harman  # The user to execute the task as
  args:
    force: yes

- name: Add EPEL repo
  yum:
    name: epel-release
  become: yes

- name: Install Node.js
  yum: 
    name: 
      - nodejs
      - npm
  become: yes

- name: Install nodemon globally
  command: npm install -g nodemon
  become: yes

- name: Install app dependencies
  become: yes
  become_user: harman
  become: true
  command: npm install
  args:
    chdir: /chatapp/client


- name: Install app dependencies
  become: yes
  become_user: harman
  become: true
  command: npm install
  args:
    chdir: /chatapp/server




- name: Build the client side
  command: npm run build
  args:
    chdir: /chatapp/client
  become_user: harman
  become: true



- name: Run the server on port 5000
  command: node index.js
  args:
    chdir: /chatapp/server/
  async: 300
  poll: 0


- name: Run the server on port 3000
  command: npm start
  args:
    chdir: /chatapp/client
  async: 300
  poll: 0
