---

- name: Install required packages
  yum:
    name:
      - httpd
      - git
    state: present

- name: Start and enable Apache service
  service:
    name: httpd
    state: started
    enabled: yes

